### ISSUE TITLE
Enabling the add-on resolves in Netflix error code M7111-1309

### ISSUE THREAD

**Issue by maxrugen** [truedread/netflix-1080p#20] opened 2018-07-06 16:55 UTC
Hey,
starting earlier today I could not play any video from Netflix anymore. Neither Google nor the support forum could provide any information about error code M7111-1309 although it kind of led me to this extension. Disabling the add-on led to me being able to watch stuff on Netflix again. No idea what caused this behavior. Any ideas?

**Comment by truedread** [comment] 2018-07-06 16:58
1309 is a generic error code for a function throwing an exception. Can I have the link to the video you were trying to play that threw the error, as well as a console log of you trying to playing the video with the extension?

**Comment by fengapappit** [comment] 2018-07-07 15:39
Hello I have the same problem with all episodes of Designated Survivor for example.
Test patterns still work as intended.
Disabling the extension makes the show run at an horrendous 540p resolution with a 300 something kbps bit-rate.
There is nothing really useful in the logs, no error.

Link : https://www.netflix.com/watch/80113647
Logs : https://i.imgur.com/0yceqJS.png

**Comment by LewisGauss** [comment] 2018-07-07 17:14
Hi, just to report to you that I have been getting the same error today, on all episodes of The People v. O.J. Simpson. When I tried to play Doctor Strange, I got another error code, M7121-1331-4027.

**Comment by BakaChinatsu** [comment] 2018-07-08 06:21
For error M7111-1309, maybe you could try disable adblock.

**Comment by LewisGauss** [comment] 2018-07-08 07:16
@BakaChinatsu unfortunately that didn't do the trick for me. But Netflix was back to working after removing the extension.

**Comment by fengapappit** [comment] 2018-07-08 11:14
@BakaChinatsu this isn't adblock related. Only Netflix-1080p leads to this error while playing.

**Comment by fengapappit** [comment] 2018-07-08 11:29
After some debugging, it seems that after the last log "Starting playback" some exceptions are thrown in the cadmium player used by the extension. I would guess that the one used by Netflix got updated and changed some data models, leading to errors during processing by the script.

**Comment by stinkteeth** [comment] 2018-07-08 22:30
I'm also getting the 1309 error on various titles that force the edge manifest, probably when it might not even be needed because there is no HD.  For example, title 70198116.

This add-on is absolutely the bees knees, but netflix seems h*ll bent on braking it every chance they get.  Thanks to the dev for fixing it so often.

By the way, is there any way to force the win10 edge 4k manifest on chrome?

**Comment by DaveLillo** [comment] 2018-07-14 18:02
I am also getting this error with many shows (couldn't find a series where it works) When i disable the Plug-In, it works fine again - just only in 720p.

Logs: [https://imgur.com/bwxmGPM](https://imgur.com/bwxmGPM)

**Comment by kamikat** [comment] 2018-07-16 18:14
The plugin works with test video but produces with M7111-1309 on other videos (with Netflix Japan).

It seems that the error is originated from [`getMetadata`](https://github.com/truedread/netflix-1080p/blob/master/get_manifest.js#L168) function call:

> No signature of method: com.netflix.cadmium.manifest.Manifest.observePlayable() is applicable for argument types: (com.netflix.api.service.video.APICachedShowImpl) values: [com.netflix.api.service.video.APICachedShowImpl@4c74945]

See [error object dump](https://gist.github.com/kamikat/94a827ea6a9114e3e8b4a58b4cf43b63) for details.

**Comment by truedread** [comment] 2018-07-16 22:32
This is a very frustrating error as it seems Netflix has changed the way it checks manifest request syntax. I'll have to re-reverse engineer the Chrome obfuscated JS and emulate its manifest requesting as much as possible now.

**Comment by truedread** [comment] 2018-07-16 22:46
Actually, I was mistaken. A closer look reveals that my extension will fail when it tries to request a season viewable ID. The Netflix playercore JS goes around this by doing an API request to get the episode viewable ID. I'll look into implementing this.

**Comment by truedread** [comment] 2018-07-16 23:04
Should be fixed in latest commit. Please reopen if any issues still occur.

**Closed by truedread** 2018-07-16 23:04 UTC

**Comment by TheRealBecks** [comment] 2018-08-08 08:06
We've used Ubuntu 16.04 with Firefox and it worked great for months. Two days ago we switched to Opensuse Tumbleweed and it also worked flawlessly. But since Yesterday we get the error M7111-1309.

We're in the middle of an episode of 'Luke Cage' and can watch that episode and also 'How I met your mother' is working great, but everything else isn't working anymore. Can I provide any more information to help you out?

Not working:
- Brooklyn Nine-Nine
- iZombie

**Comment by bdutro** [comment] 2018-08-13 20:50
I'm getting this error on Arch with Chrome 68.0.3440.106. I've tried both the master and beta branches. Some movies/shows work fine, but for example The Dark Knight gives me the M7111-1309 error.

**Comment by truedread** [comment] 2018-08-13 21:30
@bdutro Is there anything in the console?

**Comment by bdutro** [comment] 2018-08-13 22:53
Ugh, I just realized it was because uMatrix was blocking some of the scripts that were needed. The error is gone now. However, The Dark Knight is still only 480p, while other shows are giving me 1080p. Is this expected?

**Comment by Cyborgscode** [comment] 2018-12-30 20:08
happend today with : https://www.netflix.com/watch/70284278

Workaround: temp disable this addon
Cause: Movie is not available in 1080p at all
