### ISSUE TITLE
netflix streaming error: error code: M7111-1331

### ISSUE THREAD

**Issue by ijmondal** [truedread/netflix-1080p#35] opened 2018-11-27 09:20 UTC
Could not play any video. message 

> "Oops something went wrong...

> Streaming Error

> The title is not available to watch instantly. Please try another title.

 Disabling the extension solved the issue.

**Comment by nhockey** [comment] 2018-11-27 12:21
please see #30

**Comment by truedread** [comment] 2019-01-07 00:15
Duplicate of #30

**Closed by truedread** 2019-01-07 00:15 UTC
Labels: duplicate
