### ISSUE TITLE
Was Working Fine Until Today

### ISSUE THREAD

**Issue by Saad-Jalowdi** [truedread/netflix-1080p#92] opened 2020-05-11 06:47 UTC
I got this issue today the Title still loading and it would never play. 
![image](https://user-images.githubusercontent.com/46906485/81531976-5466dd80-936c-11ea-9aad-afe30d22e029.png)

**Comment by NovaPrima** [comment] 2020-05-11 08:54
Duplicate of #90

**Comment by davwheat** [comment] 2020-05-11 12:35
@NovaPrima except (as of now) I can't even play with 5.1 enabled.

**Comment by truedread** [comment] 2021-06-22 10:44
Closing as major changes have been made that have probably fixed this.

**Closed by truedread** 2021-06-22 10:44 UTC
