### ISSUE TITLE
Oops, Something Went Wrong, Unexpected Error

### ISSUE THREAD

**Issue by L0rdLogan** [truedread/netflix-1080p#34] opened 2018-11-17 22:28 UTC
Hi.

I'm having an issue with Chrome V70 and Firefox V63 where having the plugin installed and enabled generates a "Oops something went wrong, unexpected error"

Only way to resolve this is to use netflix with the plugin disabled (not great as I record content off it using OBS for Archive purposes (the netflix original shows)

**Comment by furbino** [comment] 2018-11-17 22:54
same here

**Comment by nhockey** [comment] 2018-11-18 02:16
See my thread, the error has changed but the issue is the same. #30

**Comment by dereg666** [comment] 2018-11-21 01:20
same happened to me on both chrome and firefox.

**Comment by truedread** [comment] 2018-11-21 04:40
Duplicate of #30, closing

**Closed by truedread** 2018-11-21 04:40 UTC
Labels: duplicate
