### ISSUE TITLE
Seems Netflix has "fixed" the functionality of your extension resulting in no more than 720p

### ISSUE THREAD

**Issue by nhockey** [truedread/netflix-1080p#30] opened 2018-11-15 05:38 UTC
This was working as of no less than 24h ago. Dunno what they did, nor why they are so adamant on preventing browser users from accessing 1080p content.... but none the less they seem to be at it again. It's the classic:

> Whoops, something went wrong... 
> Unexpected error
> There was an unexpected error. Please Reload the page and try again.
> Error Code M7111-1331-2206

As expected if you disable your extension it resolves the error... to a dismal pixelated mess of 480 on my big beautiful screen. If there is any further information you need feel free to message me and i'll supply you with whatever i can, within my capabilities. I've confirmed this to be happening in Windows 7, Debian 9 Stretch, and OSX Sierra on Chrome 70.xxx.xxx.xx.xxx.x (insert obfuscated non-standard revision mishmash here)

Eidt: if you're not getting the error, just F5 and it will reload with the error message.
Edit 2: Test patterns do confirm that 720p is working. However, the movie I was watching last night is a movie I know used to be available up to 1080p.

**Comment by jeyk** [comment] 2018-11-15 13:11
I can confirm this, ran into the same error today. Disabling the extension helped, I seem to at least get 720p on Fedora 29.

**Comment by pguedes** [comment] 2018-11-15 13:16
same... had to disable extension :(

**Comment by nhockey** [comment] 2018-11-17 07:39
I enabled developer mode for extensions and merged in the pull request from [https://github.com/truedread/netflix-1080p/pull/32](url) Then i loaded the customized version of the extension with the new playercore and all seems to be working correctly.

It seems that Netflix has updated from cadmium playercore 6.0009.457.011 to cadmium playercore 6.0011.474.011.

I hear there is an issue with content which isn't avaliable in 1080p; however i have not come across this issue as of yet.

> Version: 6.0011.474.011
> UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
> bitrate (a/v): 192 / 3010 (1920x1080)
>Current CDN (a/v): c001.ord001.dev.ix.nflxvideo.net, Id: 19880 / akamaitp, Id: 19
>Audio Track: en, Id: A:1:1;6;en;1;, Channels: 5.1, Codec: audio/mp4;codecs=mp4a.40.2
>Video Track: Codec: video/mp4;codecs=avc1.640028 (avc)

**Comment by ThoreauHenry** [comment] 2018-11-17 07:45
Guess I'll wait for them to push the next release out.  Thought it was upgrading Chrome to 70.x that did it.  Glad the issue has been identified.  Netflix really needs to stop treating non-Windows users like lepers.  Our OS runs their damn servers FFS.

**Comment by nhockey** [comment] 2018-11-17 07:57
> Guess I'll wait for them to push the next release out. Thought it was upgrading Chrome to 70.x that did it. Glad the issue has been identified. Netflix really needs to stop treating non-Windows users like lepers. Our OS runs their damn servers FFS.

I ammend my previous comment. i tried some of the test patterns and the problem represented itself. So this isn't a "fix" but a work around on some videos. But it @jeyk seems to be onto something.
@ThoreauHenry The problems is OS independedent it seems. I just happenend to fiddle with it in Linux because im more comfortable with vim/diff/git in unix type environments. :)

**Comment by om26er** [comment] 2018-11-17 20:01
> I hear there is an issue with content which isn't avaliable in 1080p; however i have not come across this issue as of yet.

Try Z Nation Season 2 Episode 12 to reproduce that issue https://www.netflix.com/watch/80068065?trackId=14170286

**Comment by nhockey** [comment] 2018-11-17 21:49
> > I hear there is an issue with content which isn't avaliable in 1080p; however i have not come across this issue as of yet.
> 
> Try Z Nation Season 2 Episode 12 to reproduce that issue https://www.netflix.com/watch/80068065?trackId=14170286

I used the "test patterns" to test and some of the patterns refused to play even though they were available in 1080p. But a couple 720p/480p movies play fine. So I'm thinking they are doing something with DRM on the backend to thwart piracy and they are slowly re-coding some titles and/or this new protection is working its way around to all their CDNs.  I respect the anti-piracy thing; what bothers me is that I have to drop $400 on a special device to watch something I already pay for. Hope this is resolved soon as I've reached the limits of my understanding of the issue.

**Comment by ThoreauHenry** [comment] 2018-11-17 22:25
> @ThoreauHenry The problems is OS independedent it seems. I just happenend to fiddle with it in Linux because im more comfortable with vim/diff/git in unix type environments. :)

As am I(Ubuntu 16.04).  It's not OS independent when you look at what's supported and what ain't.  

Safari: Up to 1080p (on Macs running OS X 10.10.3 or greater)

Microsoft Internet Explorer: Up to 1080p

ChromeOS Chrome:  1080p

Microsoft Edge: Up to 4K (requires HDCP 2.2-compliant connection to a 4K display, with at least Intel’s 7th gen Core CPU, plus the latest version of Windows)

Windows 10 App:  Up to 4k

You can't even WINE it, because it's OS embedded.  I suspect it's a DRM hardware acceleration shim that they want to ensure works to avoid support calls- even though the average Joe Linux is sitting on 12-16 thread CPU's.

In any case, this may take a bit of work to remedy if they are jerking with the DRM.   Although hopefully not Denuvo level work.

**Comment by nhockey** [comment] 2018-11-21 04:41
The recent merges do help some but do not fix all content. I know that [Test Patterns Season 1 Episode 1](https://www.netflix.com/title/80018499) Still results in  Error Code: M7353-5101

**Comment by truedread** [comment] 2018-11-21 04:42
I merged PR #32 to "fix" this issue, but there's still erroring on some series so I'll leave this open until I find a true fix.

**Comment by nhockey** [comment] 2018-11-21 04:45
> I merged PR #32 to "fix" this issue, but there's still erroring on some series so I'll leave this open until I find a true fix.

I've been poling around myself for days and I can't figure out why some titles just refuse to work and others are just fine; it's very strange IMO. If there is anything I can do to help, just let me know.

**Comment by truedread** [comment] 2018-11-21 04:58
I think I figured it out. Netflix changed the way manifests are requested so I'm actually replacing the profiles variable in the wrong place in the new player JS. Also, without VP9 profiles in the manifest request, Netflix denies it. After replacing the proper profiles variable and including VP9 profiles (they're included for verification - they aren't used in playback), Test Patterns works fine. I'll clean up the code and push a release in a bit.

Profiles variable should be this:

```javascript
var profiles = [
    "playready-h264mpl30-dash",
    "playready-h264mpl31-dash",
    "playready-h264mpl40-dash",
    "vp9-profile0-L30-dash-cenc",
    "vp9-profile0-L31-dash-cenc",
    "heaac-2-dash",
    "dfxp-ls-sdh",
    "simplesdh",
    "nflx-cmisc",
    "BIF240",
    "BIF320"
]
```
And I should be replacing the profiles variable on line 77771 of the player.

**Comment by truedread** [comment] 2018-11-21 05:39
Well, I was mistaken. On movies like Thor Ragnarok (where the janky extra manifest method previously worked), VP9 is actually requested instead of the other profiles. When taking out VP9, Netflix throws a cryptic error. After modding the player to print decrypted MSL responses (because for some reason error messages are encrypted), it throws this error:

```json
{"version":2,"id":5,"serverTime":1542778622406,"from":"nq_cadmium_pbo_logblobs@1.14.5/pbo-client@1.14.5","result":{"nlp":true}}
```

I have no idea what that means but I can only assume it has an issue with the fact that the client isn't getting VP9 profiles. I'll have to look into this further.

**Comment by truedread** [comment] 2018-11-21 05:47
I figured out a clever workaround. Since the new MSL API gives (pardon my french) bullshit error messages, I thought about using the legacy MSL API. Doing the same thing with the old MSL API and it tells me:

>DESCRIPTION: "Playback not permitted because device request did not include a PRK profile."

So, why not include a pointless HEVC PRK profile?

Changing the profiles variable to:

```javascript
var profiles = [
    "playready-h264mpl30-dash",
    "playready-h264mpl31-dash",
    "playready-h264mpl40-dash",
    "hevc-main10-L30-dash-cenc-prk",
    "heaac-2-dash",
    "heaac-5.1-dash",
    "simplesdh",
    "nflx-cmisc",
    "BIF240",
    "BIF320"
];
```

allows it to work on movies like Thor Ragnarok perfectly.

**Comment by truedread** [comment] 2018-11-21 05:56
Just pushed the fixing commit. I'll update the extension on the Chrome webstore. Before I close this issue, can everyone confirm my fix works? I tested Testing Patterns, Narcos: Mexico, and Thor: Ragnarok, and all worked fine.

**Comment by nhockey** [comment] 2018-11-21 06:04
i was trying to hack in what you said when i was just like "ah, to hell with it!" 
![remember when this was three lines of code?](https://user-images.githubusercontent.com/436149/48821820-c8509880-ed28-11e8-9048-82f00fd8ffd3.png)
Remember when that was just a few lines of code? This is getting out of control!
Thank you so much for saving my sanity, and probably loosing a bit of your own along the way. 
:+1:

**Comment by truedread** [comment] 2018-11-21 06:10
I remember the good days when this extension was nothing more than a one-line fix, and, I lost my sanity the second I made get-manifest.js

But on a serious note, this workaround relies on a huge oversight. Netflix could break this extension again if they choose, which means I'm going to have to find time in my schedule to sit down and fix it again, and who knows how long that will take. I'm starting to get seriously concerned for the future of this extension as if it breaks and I take longer than a week to fix it, the userbase would take a huge hit.

**Comment by nhockey** [comment] 2018-11-21 06:19
It seems you have plenty of people who are using this extension whom would be willing to offer you support any way they can. Who knows, maybe one day they will just let people using Chrome just have access to content greater than 720p? Thank you so much for spending time making this work again. Hopefully, Netflix will simply calm down about the whole thing and you'll be able to get a good nights rest. :smile:

**Comment by nhockey** [comment] 2018-11-21 07:35
> So everything works? Just want to make sure.
> 
> Also, for posterity, I just want to report that the new MSL API actually does give full error messages. Here's what the PRK error message looks like from the new MSL API:
> 
> ```json
> {"version":2,"id":15427813743298,"serverTime":1542781389452,"from":"nq_cadmium_pbo_manifests@1.14.4/pbo-client@1.14.4","error":{"pboc":true,"code":"FAIL","detail":"manifest/pbcs-445: Playback not permitted because device request did not include a PRK profile. (nq_cadmium_pbo_manifests@1.14.4/pbo-client@1.14.4)","display":"This title is not available to watch instantly. Please try another title.","errorDisplayMessage":"This title is not available to watch instantly. Please try another title.","errorActionId":3,"nccpError":{},"errorSubCode":0,"errorReasonCode":0,"errorNccpCode":0,"errorExternalCode":0,"bladeRunnerMessage":"manifest/pbcs-445: Playback not permitted because device request did not include a PRK profile. (nq_cadmium_pbo_manifests@1.14.4/pbo-client@1.14.4)","bladeRunnerCode":"445"}}
> ```

I checked everything people had reported not working including 16:9 stuff 4:3 stuff... I can't find anything that's not working. I'll reopen it for the time being just so people can report anything else. But I think you nailed it.

**Comment by Aspectsec** [comment] 2018-11-21 16:17
Can confirm that it does not play more than 720p, just compared bitrates and stuff. 

Thanks for your work man.

**Comment by truedread** [comment] 2018-11-21 18:10
@Aspectsec it doesn't play more than 720p? What series did you try?

**Comment by jeyk** [comment] 2018-11-21 18:23
@truedread Awesome work, thanks a lot! I just tried four different programmes, all played instantly and in 1080p.

About your concerns for the future of this extension: I am pretty much depending on it (because I don't want to boot Windows every time I want to watch Netflix for an hour), so I will definitely try to help, should it break again. The problem is that at the moment I understand almost nothing of the stuff you are talking about. What is the "MSL API" and is there some documentation about it?

**Comment by truedread** [comment] 2018-11-21 18:39
The MSL API is Netflix's E2E-encrypted API they use for requesting manifests and licenses. It's somewhat documented over here: https://github.com/Netflix/msl/wiki, but that's just for a general MSL implementation. To actually see how Netflix's implementation works you just have to reverse engineer it. I've written tools to interact with it, though. Like `get_manifest.js` in this repo or https://github.com/truedread/pymsl.

**Comment by phaax** [comment] 2018-11-21 19:40
cadmium-playercore-6.0011.**474.011** worked for a few days.. Then it stopped working. Netflix has updated it to 6.0011.**511.011** :(

I've followed the instructions in the readme.md and tried to patch the new version, but I couldn't get it to work. It fails after (successfully) acquiring an Edge manifest, but the playback never starts. Endless spinning circle.

**Comment by truedread** [comment] 2018-11-21 22:21
@phaax What series?

@caphm A fix would be to use a constant ESN per device instead of randomly generating it every time a new video is played. I would try to implement but I haven't encountered this error yet.

**Comment by Elanzer47** [comment] 2018-11-21 23:40
Working fine here, thanks for your hard work.

**Comment by caphm** [comment] 2018-11-21 23:43
@truedread I have implemented this fix for the Kodi Netflix plugin and can confirm it works. If you ever encounter it, you know how to solve it ;)

**Comment by prasoc** [comment] 2018-11-22 08:49
@caphm i am unsure as to whether i should use the extension until this has been sorted. What is the upper-limit value? and can you get rid of that error somehow?

**Comment by caphm** [comment] 2018-11-22 09:08
@prasoc I don't know the upper limit value. It seems like it's also dependant on the timeframe in which the requests are made. If you're not using this every couple seconds (like I was for testing purposes), your should be fine.

**Comment by Aspectsec** [comment] 2018-11-22 10:03
> @Aspectsec it doesn't play more than 720p? What series did you try?

I tries many : Narcos, naruto shippuden, Ozark, ... on chrome with your extension then on Edge. No more than 720p on chrome whereas on edge it played 1080p.

**Comment by fragmental** [comment] 2018-11-22 15:48
I reenabled the plug in and now I'm getting the error "This title is not available to watch instantly" on many, but not all, movies.  Most of the Marvel movies, the Pirates of the Caribbean Movies, and the Star Wars Movies are the ones I have tested that have this error .  The error code is M7121-1331

Also, how are people checking the resolution?  I've been using ctrl-shift-s but that only shows me the bit rate and for some videos it seems wrong, because it will say the bit rate is low like 600 but it doesn't look that low.

**Comment by ItsNickBarry** [comment] 2018-11-22 16:18
@fragmental `ctrl` + `alt` + `shift` + `D`

**Comment by truedread** [comment] 2018-11-23 06:12
Oh boy, Netflix fixed my little workaround. Movies where the manifest has to be acquired separately no longer work and I'm trying to think of another workaround.

Thanks Netflix.

**Comment by Aspectsec** [comment] 2018-11-23 08:35
> 10

So you'd have to fake the request being sent from Edge of whatever ?

**Comment by truedread** [comment] 2018-11-24 03:44
The request is already being sent from an Edge ESN, but you can't perform a Widevine license request with an Edge ESN. Previously, since the keys for AVC Main were shared between resolutions, I would just do a Widevine license request with a Chrome ESN for SD AVC Main, and then get the 1080p AVC Main MP4 links with an Edge ESN and use those for playback. However, Netflix now doesn't allow Chrome to get a license for anything AVC Main on those videos, so I'm stuck. I'm just gonna update the extension to use AVC-Hi on those videos so it can at least play 720p instead of SD until I can think of a solution.

**Comment by shugo-chara** [comment] 2018-11-24 07:52
Seems that the v1.12 version does not work in some movies, error M7353-5101, even the 720 can not watch，but working fine on other videos（1080p）

**Comment by truedread** [comment] 2018-11-24 08:46
Which movies?

**Comment by shugo-chara** [comment] 2018-11-24 14:08
> Which movies?

Anime The Asterisk War S1

**Comment by hchr** [comment] 2018-11-24 16:01
I tested a few of Netflix own productions. They work in 1080p. Friends and Passengers fail with M7353-5101. Breaking Bad is 1080p.

**Comment by FvckWize** [comment] 2018-11-24 20:10
v1.12 works, but only on a few titles. I haven't gotten any "Unable to watch" errors, I just haven't been able to pass 720p.

**Comment by fragmental** [comment] 2018-11-26 01:32
The Never Ending Story and Johnny English Reborn also fail with M7353-5101

**Comment by caphm** [comment] 2018-11-27 08:37
Netflix seems to have made some changes to the quality that some titles are available in. Titles previously available in 1080p (no addons) are now only available in SD.
For me this affects American Horror Story and American Crime Story. I suspect there are others affected as well.

**Comment by stinkteeth** [comment] 2018-12-01 14:45
> Netflix now doesn't allow Chrome to get a license for anything AVC Main

What is the default widevine license that netflix current permits acquisition for streaming on chrome?  Is it AVC-Hi w/o prk?  Are you saying that AVC Main license acquisition is gone for streaming on chrome in the default player? Or is this just the case on some videos where the edge manifest was required in order to get the edge playready 1080p sources? What are the names of the AVC-Hi profiles used by the default player?

I'm trying to understand the new license acquisition configuration on chrome.  Thanks.

**Comment by fragmental** [comment] 2018-12-01 19:50
It seems as though some of the videos that fail to play with the extension will only play in 480p in Microsoft Edge.  To play in 1080p requires using an official Netflix app

**Comment by tuxmark5** [comment] 2018-12-02 12:33
All videos in Linux now seem to play 480p. With extension enabled videos don't load at all (it just keeps loading forever). The extension works fine in windows and i get 1080p with extension or 720p with no extension.

**Comment by om26er** [comment] 2018-12-02 12:51
> All videos in Linux now seem to play 480p. With extension enabled videos don't load at all (it just keeps loading forever). The extension works fine in windows and i get 1080p with extension or 720p with no extension.

Try refreshing the page. I have come across cases where the video would initially play in low rest with maximum supported bitrate to be of 480p rest slab. A refresh fixes that to 1080p

**Comment by tuxmark5** [comment] 2018-12-02 13:01
> Try refreshing the page. I have come across cases where the video would initially play in low rest with maximum supported bitrate to be of 480p rest slab. A refresh fixes that to 1080p

After some testing, I've found that some videos play fine with 1080p with plugin. Some videos that worked fine a while ago (such as Good Place) don't work anymore and I get error M7353-5101. And others, like The Sinner don't seem to load at all (but after some fiddling I get M7111-1309 now instead of the perpetual loading screen).

**Comment by ThoreauHenry** [comment] 2018-12-03 07:35
Trying another angle, I attempted a virtualbox session with W10/Edge, due to the recent release(6.0 b3) of a high definition video driver, but it seems that doesn't work on my hardware quite yet.  

https://www.phoronix.com/scan.php?page=news_item&px=VirtualBox-6.0-Beta-3

I'll have to look at doing gpu passthrough to an nvidia 10 series card and see if that does the trick.  I'm not on a intel 7th gen+ cpu, so I can't PAE/NX cpu passthrough to that hardware, as those are the 2 pc requirements for hd/hdr.  

This seems to be alot of work for a service I'm paying for.  At the end of the day, even the Apple's won't work without the app, as they are AMD/radeon now- and that doesn't make the cut for decoding DRM.  I heard rumor that netflix and google are pulling the sheets out from each other, so I'm not even sure how long those chrome supported apps will last either.  They seem to have a permanent hardon for Microsoft.  I'll update when it works/fails.  IOMMU passthrough should get the job done, but it's a long way off from a browser addon.

**Comment by xf-** [comment] 2019-01-30 19:50
Somebody tried to "use" Chrome OS? HTML5 player supports 1080p on Chrome at Chrome OS
https://help.netflix.com/de/node/23742

**Comment by mqudsi** [comment] 2019-03-13 11:41
@truedread presumably Netflix is going to make some big changes soon that might help you considerably, as future updates to Edge will see it move to Chrome under the hood. I'm sure there will still be Edge/Microsoft-specific DRM, but it may lead to easier circumvention.

**Comment by truedread** [comment] 2019-07-20 12:58
@mqudsi you were quite right. Wanna try again now guys?

**Closed by truedread** 2019-07-20 12:58 UTC
